INSERT INTO "doenca" ("ID_DOENCA","NOME_DOENCA","DESCRICAO","SINTOMAS","FLG_COMUM","FLG_TRATACOMVACINA","FLG_TRATADOPORPESSOA","FLG_PROPAGAFACIL","FLG_REQUEREXAME","MEDIADIASCURA","FLG_GRAVE") VALUES (1,'cancer','mata','morre',1,0,0,0,1,0,1);
GO
